name: build
on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '16.0.1'

      - name: Build Tests
        run: |
          javac -d bin -cp "lib/*:." -sourcepath src ./src/**/**/*.java
          mkdir -p $GITHUB_WORKSPACE/bin
          cp -r bin/* $GITHUB_WORKSPACE/bin
          
      - name: Run Tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.9.0.jar --class-path bin --scan-class-path --fail-if-no-tests -cp $GITHUB_WORKSPACE/bin
        # execute your tests generating test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "reports/**/*.xml"
